name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_shishir
          chmod 600 ~/.ssh/id_rsa_shishir
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to server
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # server's IP address
          username: ${{ secrets.SERVER_USERNAME }} # server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # server's SSH private key
          passphrase: ${{ secrets.PASSPHRASE }} # server's SSH private key passphrase
          script: |
            cd /root/projects/wanderpokhara/wanderpokhara-admin-panel/
            git pull origin main
            sudo npm ci
            sudo npm run build
            pm2 restart admin-wanderpokhara
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
